version: '3.8'

services:
  django:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    restart: always
    ports:
      - 8000:8000
    env_file:
      - .env
    volumes:
      - ./:/app
    container_name: django_app_dmitry